/*
 * This source file was generated by the Gradle 'init' task
 */
package org.inertiagraphics.inertia

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        // val classUnderTest = Inertia()
        assertTrue(true, "someLibraryMethod should return 'true'")
    }
}
